language: ruby
sudo: false
cache: bundler
script:
  - bundle exec rspec
rvm:
  - 2.3.4
  - 2.4.1
  - jruby-9.1.8.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fde2367248d53de4fe70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always
